server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    tomcat:
      test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: validate
liquibase.change-log: classpath:db/changelog/db.changelog.xml
logging:
  level: info